import { NgModule } from '@angular/core';

import {
    TUI_SANITIZER,
    TuiAutoFocusModule,
    TuiElementModule,
    TuiFilterPipeModule,
    TuiLetModule,
    TuiMapperPipeModule,
    TuiMediaModule,
} from '@taiga-ui/cdk';
import {
    TuiButtonModule,
    TuiCalendarModule,
    TuiColorModule,
    TuiDataListModule,
    TuiDialogModule,
    TuiDropdownControllerModule,
    TuiDropdownModule,
    TuiErrorModule,
    TuiExpandModule,
    TuiFormatNumberPipeModule,
    TuiFormatPhonePipeModule,
    TuiGroupModule,
    TuiHintControllerModule,
    TuiHintModule,
    TuiHostedDropdownModule,
    TuiLabelModule,
    TuiLinkModule,
    TuiLoaderModule,
    TuiManualHintModule,
    TuiModeModule,
    TuiNotificationModule,
    TuiNotificationsModule,
    TuiPointerHintModule,
    TuiPrimitiveCheckboxModule,
    TuiPrimitiveTextfieldModule,
    TuiRootModule,
    TuiScrollbarModule,
    TuiSvgModule,
    TuiSvgService,
    TuiTextfieldControllerModule,
    TuiTooltipModule,
} from '@taiga-ui/core';
import {
    TuiAccordionModule,
    TuiActionModule,
    TuiAvatarModule,
    TuiBadgedContentModule,
    TuiBadgeModule,
    TuiBreadcrumbsModule,
    TuiCalendarMonthModule,
    TuiCalendarRangeModule,
    TuiCheckboxBlockModule,
    TuiCheckboxLabeledModule,
    TuiCheckboxModule,
    TuiComboBoxModule,
    TuiDataListWrapperModule,
    TuiDropdownSelectionModule,
    TuiFieldErrorModule,
    TuiFilterModule,
    TuiHighlightModule,
    TuiInputCopyModule,
    TuiInputCountModule,
    TuiInputDateModule,
    TuiInputDateRangeModule,
    TuiInputDateTimeModule,
    TuiInputFileModule,
    TuiInputInlineModule,
    TuiInputModule,
    TuiInputMonthModule,
    TuiInputMonthRangeModule,
    TuiInputNumberModule,
    TuiInputPasswordModule,
    TuiInputPhoneInternationalModule,
    TuiInputPhoneModule,
    TuiInputRangeModule,
    TuiInputSliderModule,
    TuiInputTagModule,
    TuiInputTimeModule,
    TuiIslandModule,
    TuiLazyLoadingModule,
    TuiLineClampModule,
    TuiMarkerIconModule,
    TuiMultiSelectModule,
    TuiPaginationModule,
    TuiPresentModule,
    TuiRadioBlockModule,
    TuiRadioLabeledModule,
    TuiRadioListModule,
    TuiRadioModule,
    TuiSelectModule,
    TuiSliderModule,
    TuiStepperModule,
    TuiTabsModule,
    TuiTagModule,
    TuiTextAreaModule,
    TuiToggleModule,
} from '@taiga-ui/kit';

import * as icons from '@taiga-ui/icons';

import {
    TuiAxesModule,
    TuiBarChartModule,
    TuiLineChartModule,
    TuiLineDaysChartModule,
    TuiPieChartModule,
    TuiRingChartModule,
} from '@taiga-ui/addon-charts';

import {
    TuiReorderModule,
    TuiResizableColumnModule,
    TuiTablePaginationModule,
    TuiTableModule,
} from '@taiga-ui/addon-table';
import { PolymorpheusModule } from '@tinkoff/ng-polymorpheus';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';

@NgModule({
    exports: [
        TuiAutoFocusModule,
        TuiElementModule,
        TuiFilterPipeModule,
        TuiLetModule,
        TuiMapperPipeModule,
        TuiMediaModule,
        PolymorpheusModule,
        FormsModule,
        ReactiveFormsModule,
        TuiAxesModule,
        TuiBarChartModule,
        TuiLineChartModule,
        TuiLineDaysChartModule,
        TuiPieChartModule,
        TuiRingChartModule,
        TuiAccordionModule,
        TuiActionModule,
        TuiAvatarModule,
        TuiBadgedContentModule,
        TuiBadgeModule,
        TuiBreadcrumbsModule,
        TuiCalendarMonthModule,
        TuiCalendarRangeModule,
        TuiCheckboxBlockModule,
        TuiCheckboxLabeledModule,
        TuiCheckboxModule,
        TuiComboBoxModule,
        TuiDataListWrapperModule,
        TuiDropdownSelectionModule,
        TuiFieldErrorModule,
        TuiFilterModule,
        TuiHighlightModule,
        TuiInputCopyModule,
        TuiInputCountModule,
        TuiInputDateModule,
        TuiInputDateRangeModule,
        TuiInputDateTimeModule,
        TuiInputFileModule,
        TuiInputInlineModule,
        TuiInputModule,
        TuiInputMonthModule,
        TuiInputMonthRangeModule,
        TuiInputNumberModule,
        TuiInputPasswordModule,
        TuiInputPhoneInternationalModule,
        TuiInputPhoneModule,
        TuiInputRangeModule,
        TuiInputSliderModule,
        TuiInputTagModule,
        TuiInputTimeModule,
        TuiIslandModule,
        TuiLazyLoadingModule,
        TuiLineClampModule,
        TuiMarkerIconModule,
        TuiMultiSelectModule,
        TuiPaginationModule,
        TuiPresentModule,
        TuiRadioBlockModule,
        TuiRadioLabeledModule,
        TuiRadioListModule,
        TuiRadioModule,
        TuiSelectModule,
        TuiSliderModule,
        TuiStepperModule,
        TuiTabsModule,
        TuiTagModule,
        TuiTextAreaModule,
        TuiToggleModule,
        TuiButtonModule,
        TuiCalendarModule,
        TuiColorModule,
        TuiDataListModule,
        TuiDialogModule,
        TuiDropdownControllerModule,
        TuiDropdownModule,
        TuiErrorModule,
        TuiExpandModule,
        TuiFormatNumberPipeModule,
        TuiFormatPhonePipeModule,
        TuiGroupModule,
        TuiHintControllerModule,
        TuiHintModule,
        TuiHostedDropdownModule,
        TuiLabelModule,
        TuiLinkModule,
        TuiLoaderModule,
        TuiManualHintModule,
        TuiModeModule,
        TuiNotificationModule,
        TuiNotificationsModule,
        TuiPointerHintModule,
        TuiPrimitiveCheckboxModule,
        TuiPrimitiveTextfieldModule,
        TuiRootModule,
        TuiScrollbarModule,
        TuiTextfieldControllerModule,
        TuiTooltipModule,
        TuiReorderModule,
        TuiResizableColumnModule,
        TuiTablePaginationModule,
        TuiTableModule,
    ]
})

export class TaigaModule { }
